import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({viewport:{width:1440,height:1200}});
await page.goto('http://localhost:8912/#fleet',{waitUntil:'networkidle'});
await page.waitForTimeout(3000);
console.log('=== BEFORE ===\n' + (await page.locator('body').innerText()).slice(0,400));
await page.route('**/benzene/invoke', r => r.abort('failed'));
await page.waitForTimeout(80000);
console.log('\n=== AFTER 40s OF FAILED POLLS ===\n' + (await page.locator('body').innerText()).slice(0,700));
await browser.close();
