import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1800 } });
await page.goto('http://localhost:8930/', { waitUntil: 'networkidle' });
await page.waitForTimeout(2000);
const btns = await page.getByRole('button', { name: 'show', exact: true }).all();
console.log("show buttons:", btns.length);
await btns[btns.length-1].click();
await page.waitForTimeout(2500);
const t = await page.locator('body').innerText();
console.log(t.split('Topology')[1]?.slice(0,3000));
await page.locator('text=Topology').first().scrollIntoViewIfNeeded();
await page.waitForTimeout(500);
await page.screenshot({ path: '/tmp/claude-0/-home-user-Benzene/77b3f3e3-e32a-52a7-bd95-4e3fccac2f7b/scratchpad/shots/15-topology.png', fullPage: true });
await browser.close();
