import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1600 } });
await page.goto('http://localhost:8930/', { waitUntil: 'networkidle' });
await page.waitForTimeout(2000);
await page.getByRole('button', { name: /^payment:capture$/ }).nth(0).click();
await page.waitForTimeout(2000);
console.log("=== v2 tab ===");
await page.getByRole('button', { name: /^v2$/ }).nth(0).click();
await page.waitForTimeout(2000);
console.log(await page.locator('body').innerText());
await page.screenshot({ path: '/tmp/claude-0/-home-user-Benzene/77b3f3e3-e32a-52a7-bd95-4e3fccac2f7b/scratchpad/shots/10-payment-v2.png', fullPage: true });
console.log("=== change live window to 24h ===");
await page.selectOption('select[aria-label="Live window"]', { label: '24 hours' }).catch(e=>console.log("selopt fail", e.message));
await page.waitForTimeout(3000);
const txt = await page.locator('body').innerText();
console.log(txt.split('TRAFFIC')[1]?.slice(0,900));
await page.screenshot({ path: '/tmp/claude-0/-home-user-Benzene/77b3f3e3-e32a-52a7-bd95-4e3fccac2f7b/scratchpad/shots/11-payment-v2-24h.png', fullPage: true });
await browser.close();
