import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1600 } });
await page.goto('http://localhost:8930/', { waitUntil: 'networkidle' });
await page.waitForTimeout(2000);
console.log("=== click flow a71c... ===");
await page.getByText('a71c4f0b2e779d31').first().click();
await page.waitForTimeout(2500);
console.log("URL:", page.url());
console.log(await page.locator('body').innerText());
await page.screenshot({ path: '/tmp/claude-0/-home-user-Benzene/77b3f3e3-e32a-52a7-bd95-4e3fccac2f7b/scratchpad/shots/13-flow.png', fullPage: true });
await browser.close();
