import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1600 } });
await page.goto('http://localhost:8930/', { waitUntil: 'networkidle' });
await page.waitForTimeout(2000);
await page.getByRole('button', { name: 'Changes', exact: true }).click();
await page.waitForTimeout(1500);
await page.locator('select').nth(1).selectOption({ label: 'orders-api' });
await page.waitForTimeout(1500);
const t = await page.locator('body').innerText();
console.log("=== ROLLOUTS filtered orders-api ===");
console.log(t.split('Field changes')[1]);
await page.screenshot({ path: '/tmp/claude-0/-home-user-Benzene/77b3f3e3-e32a-52a7-bd95-4e3fccac2f7b/scratchpad/shots/20-changes-orders.png', fullPage: true });
// also try state filter
await page.locator('select').nth(1).selectOption({ label: 'All services' });
await page.waitForTimeout(800);
await page.locator('select').nth(2).selectOption({ label: 'move outstanding' });
await page.waitForTimeout(1200);
const t2 = await page.locator('body').innerText();
console.log("=== filtered state=move outstanding ===");
console.log(t2.split('Field changes')[1]?.slice(0,1500));
await browser.close();
