import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1400 } });
page.on('pageerror', e => console.log('PAGE ERR: '+e.message));
const reqs=[];
page.on('request', r => { if (r.method()!=='GET') reqs.push(r.method()+' '+r.url()+' :: '+(r.postData()||'').slice(0,400)); });
await page.goto('http://localhost:8930/#compose/payment%3Acapture', { waitUntil: 'networkidle' });
await page.waitForTimeout(1200);
await page.locator('input[type=checkbox]').check();
await page.waitForTimeout(300);
await page.getByRole('button', { name: /^Send/ }).click();
await page.waitForTimeout(3500);
console.log('=== BODY AFTER SEND (v2) ===');
console.log(await page.locator('body').innerText());
console.log('=== NETWORK ===\n'+reqs.join('\n'));
await page.screenshot({ path:'/tmp/claude-0/-home-user-Benzene/77b3f3e3-e32a-52a7-bd95-4e3fccac2f7b/scratchpad/shots/send-v2.png', fullPage:true });
await browser.close();
