import { chromium } from 'playwright';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport:{width:1440,height:1400} });
const p = await ctx.newPage();
await p.goto('http://localhost:8930/#compose/payment%3Acapture', { waitUntil:'networkidle' });
await p.waitForTimeout(1200);
console.log('=== STATE 1: malformed json ===');
await p.locator('textarea').nth(1).fill('{"orderId": ');
await p.waitForTimeout(600);
console.log((await p.locator('body').innerText()).split('Headers')[1]);
console.log('=== STATE 2: send a good one ===');
await p.locator('textarea').nth(1).fill('{"orderId":"11111111-1111-1111-1111-111111111111","amount":12.5,"currency":"GBP"}');
await p.locator('input[type=checkbox]').check();
await p.getByRole('button',{name:/^Send/}).click();
await p.waitForTimeout(2500);
console.log((await p.locator('body').innerText()).split('Headers')[1]);
console.log('=== STATE 3: now edit body to something else WITHOUT sending ===');
await p.locator('textarea').nth(1).fill('{"orderId":"DIFFERENT","amount":-999}');
await p.waitForTimeout(900);
console.log((await p.locator('body').innerText()).split('Headers')[1]);
console.log('=== STATE 4: switch payload version to v1 WITHOUT sending ===');
await p.locator('select').nth(1).selectOption('v1');
await p.waitForTimeout(900);
console.log((await p.locator('body').innerText()).split('Headers')[1]);
await ctx.close(); await browser.close();
