import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1400 } });
page.on('pageerror', e => console.log('PAGE ERR: '+e.message));
await page.goto('http://localhost:8930/#fleet', { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
await page.getByText('payment:capture', { exact: true }).first().click();
await page.waitForTimeout(2000);
console.log('URL:', page.url());
console.log(await page.locator('body').innerText());
console.log('=== LINKS ===');
const links = await page.locator('a').evaluateAll(as => as.map(a => (a.getAttribute('href')||'')+' :: '+a.innerText.replace(/\n/g,' ').slice(0,50)));
console.log([...new Set(links)].join('\n'));
console.log('=== BUTTONS ===');
const b = await page.locator('button').evaluateAll(bs => bs.map(x=>x.innerText.replace(/\n/g,' ').slice(0,60)));
console.log([...new Set(b)].join(' | '));
console.log('=== SELECTS ===');
const s = await page.locator('select').evaluateAll(ss => ss.map(x=>x.outerHTML.slice(0,300)));
console.log(s.join('\n'));
await browser.close();
